export type ToolConfig = {
  slug: string;
  navLabel: string;
  eyebrow: string;
  title: string;
  description: string;
  promise: string;
  primaryCta: string;
  secondaryCta: string;
  uploadLabel: string;
  supported: string;
  controls: Array<{
    label: string;
    value: string;
    helper: string;
  }>;
  steps: string[];
  pains: string[];
  outputFacts: Array<{ label: string; value: string }>;
  limit: string;
  related: Array<{ label: string; href: string }>;
  faq: Array<{ q: string; a: string }>;
  converter?: {
    mode: "icon" | "logo" | "extrude" | "structured" | "sketch" | "relief" | "heightmap" | "lithophane";
    accept?: string;
    widthMm?: number;
    depth?: number;
    baseMm?: number;
    threshold?: number;
    smoothing?: number;
    detail?: number;
    invert?: boolean;
    minThicknessMm?: number;
    maxThicknessMm?: number;
    hiddenControls?: Array<"mode" | "threshold" | "base" | "invert" | "depth">;
    helper: string;
    preview: string;
    filename: string;
  };
};

export const tools: ToolConfig[] = [
  {
    slug: "png-to-stl",
    navLabel: "PNG entry",
    eyebrow: "Format-specific starting point",
    title: "PNG to STL Converter",
    description: "A PNG-focused image-to-STL workflow for transparent logos, icons, stamps, silhouettes, and simple graphics that need clean solid raised geometry.",
    promise: "Use this page when alpha transparency, flat colors, and crisp edges matter more than photo detail.",
    primaryCta: "Upload PNG",
    secondaryCta: "Use Universal Converter",
    uploadLabel: "Drag and drop your PNG here",
    supported: "PNG; use Image to STL for JPG/WebP/GIF/BMP",
    controls: [
      { label: "Depth", value: "58%", helper: "Higher depth creates taller relief." },
      { label: "Size", value: "96 mm", helper: "Set the printable width." },
      { label: "Invert heightmap", value: "Off", helper: "Switch raised and recessed areas." },
    ],
    steps: ["Upload your PNG.", "Adjust depth, size, and inversion.", "Download your STL."],
    pains: ["No CAD learning curve.", "No confusing multi-tool interface.", "No guessing what the output is."],
    outputFacts: [
      { label: "Format", value: "PNG -> STL" },
      { label: "Type", value: "Clean logo badge" },
      { label: "Color", value: "Geometry only" },
    ],
    limit: "This tool creates front-facing relief STL geometry. STL files do not preserve PNG colors or textures.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Backlit Photo Panel", href: "/lithophane-generator" },
      { label: "Image Contrast Guide", href: "/image-contrast-guide" },
    ],
    faq: [
      { q: "Is this a real 3D model?", a: "It creates a relief-style STL based on PNG brightness and transparency, not a CAD reconstruction." },
      { q: "How is transparent PNG handled?", a: "Transparent or empty areas are treated as background so icons and silhouettes can become cleaner raised relief plates." },
      { q: "What PNG images work best?", a: "Flat icons, black-and-white art, emojis, stamps, silhouettes, and simple logos usually work better than noisy screenshots." },
      { q: "Why keep a PNG page if Image to STL accepts more formats?", a: "PNG users often need alpha transparency, crisp edges, and icon-style defaults. The universal converter remains the best broad-format entry." },
    ],
  },
  {
    slug: "image-to-stl",
    navLabel: "Image to STL",
    eyebrow: "Universal image to STL converter",
    title: "Image to STL Converter for 3D Printing",
    description: "Convert PNG, JPG, WebP, GIF, or BMP into the safest printable STL workflow: clean logo extrusion, PNG to STL badge, photo relief, lithophane, or heightmap surface.",
    promise: "Start here for the broad image-to-STL workflow, then route PNGs, photos, logos, and heightmaps to the best printable output.",
    primaryCta: "Convert Image to STL",
    secondaryCta: "Choose STL Mode",
    uploadLabel: "Drop an image to check the best STL workflow",
    supported: "PNG, JPG, WebP, GIF, BMP",
    controls: [
      { label: "Contrast", value: "64%", helper: "Boost edge separation before conversion." },
      { label: "Depth", value: "42%", helper: "Control relief height." },
      { label: "Output size", value: "120 mm", helper: "Keep prints within your bed size." },
    ],
    steps: ["Upload an image.", "Adjust contrast and depth.", "Download the STL."],
    pains: ["Clear guidance on which images work best.", "Less trial and error before printing.", "A single page for image-to-STL intent."],
    outputFacts: [
      { label: "Format", value: "Image → STL" },
      { label: "Best for", value: "Logos, icons, high contrast art" },
      { label: "Output", value: "Raised STL panel" },
    ],
    limit: "The universal converter creates printable STL workflows from one image; it does not reconstruct a full 3D object from a single photo.",
    related: [
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Photo to STL", href: "/photo-to-stl" },
      { label: "AI Image to 3D", href: "/ai-image-to-3d" },
      { label: "Relief Settings", href: "/image-to-stl-relief-settings" },
      { label: "Contrast Guide", href: "/image-contrast-guide" },
      { label: "Convert Image to STL", href: "/convert-image-to-stl" },
    ],
    faq: [
      { q: "What images work best?", a: "Simple, high-contrast images with clear subjects usually produce cleaner relief or lithophane output." },
      { q: "Which mode should I choose?", a: "Use raised-surface mode for icons and simple art, logo mode for badges, backlit photo panel mode for photos, and depth-map mode for grayscale depth maps." },
      { q: "Can every photo become a model?", a: "No. A single image can become a raised surface, backlit photo panel, or depth-map-style STL, but not a full reconstructed 3D object." },
      { q: "Do colors appear in the STL?", a: "No. STL is single-material geometry. Brightness, contrast, and transparency influence shape, not color output." },
    ],
  },
  {
    slug: "convert-image-to-stl",
    navLabel: "Convert Image",
    eyebrow: "Step-by-step converter",
    title: "Convert Image to STL",
    description: "A guided image-to-STL workflow for beginners who need to check image quality, choose relief settings, preview limits, and download a printable STL.",
    promise: "Check the image, tune relief depth, and prepare a printable STL.",
    primaryCta: "Start Conversion",
    secondaryCta: "Check Image First",
    uploadLabel: "Upload image to start the checklist",
    supported: "PNG, JPG, WebP, GIF, BMP",
    controls: [
      { label: "Image clarity", value: "Good", helper: "Clear edges help the relief." },
      { label: "Relief depth", value: "Medium", helper: "Balanced height for beginner prints." },
      { label: "Base plate", value: "On", helper: "Adds a printable foundation." },
    ],
    steps: ["Upload an image.", "Run the suitability checklist.", "Generate a beginner-friendly STL."],
    pains: ["Explains what to fix before converting.", "Avoids blind uploads to generic converters.", "Keeps beginners focused on printable output."],
    outputFacts: [
      { label: "Workflow", value: "Guided" },
      { label: "Output", value: "Raised STL panel" },
      { label: "Focus", value: "3D printing" },
    ],
    limit: "This guided page does not create a full 3D object from a single photo.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Print Settings", href: "/print-settings-checker" },
    ],
    faq: [
      { q: "Why use this instead of the direct converter?", a: "It adds a checklist for image suitability before you generate the STL." },
      { q: "Does it change the output type?", a: "No. It still creates relief-style STL output." },
    ],
  },
  {
    slug: "lithophane-generator",
    navLabel: "Photo Panel",
    eyebrow: "Photo light panel tool",
    title: "Backlit Photo Panel Generator",
    description: "Create 3D printable backlit STL panels from photos, set safe thickness ranges, preview backlit detail, and download a panel ready for slicer checks.",
    promise: "Set thickness, invert the image, preview backlit detail, and download the result.",
    primaryCta: "Make Photo Panel",
    secondaryCta: "Download STL",
    uploadLabel: "Upload your photo panel image",
    supported: "PNG, JPG, WebP, GIF, BMP; high contrast recommended",
    controls: [
      { label: "Min thickness", value: "0.8 mm", helper: "Thin areas transmit more light." },
      { label: "Max thickness", value: "3.2 mm", helper: "Thick areas block more light." },
      { label: "Invert image", value: "On", helper: "Usually needed for backlit panels." },
    ],
    steps: ["Upload your photo.", "Set thickness and inversion.", "Download the backlit STL panel."],
    pains: ["Clear settings for photo prints.", "Easier than CAD for photo panels.", "Explains print setup before download."],
    outputFacts: [
      { label: "Type", value: "Backlit STL panel" },
      { label: "Use", value: "Backlit photo print" },
      { label: "Mode", value: "Relief thickness" },
    ],
    limit: "Backlit photo panel results depend on image contrast, thickness, and print settings.",
    related: [
      { label: "Photo to Backlit Panel", href: "/photo-to-lithophane" },
      { label: "Best Photo Panel Settings", href: "/best-lithophane-settings" },
      { label: "3D Print Photo", href: "/3d-print-photo" },
      { label: "Print Settings", href: "/print-settings-checker" },
    ],
    faq: [
      { q: "Should backlit panels be inverted?", a: "Often yes, because thickness controls how much light passes through." },
      { q: "What makes a good photo panel?", a: "Photos with clear subjects and balanced contrast usually work best." },
    ],
  },
  {
    slug: "photo-to-lithophane",
    navLabel: "Photo Lithophane",
    eyebrow: "Photo-specific lithophane path",
    title: "Photo to Backlit Panel",
    description: "Turn a portrait or photo into a lithophane-style STL for backlit 3D printing with contrast checks, panel sizing, and thickness guidance.",
    promise: "Preview photo contrast, set thickness, and prepare a lithophane STL.",
    primaryCta: "Upload Photo",
    secondaryCta: "Check Photo",
    uploadLabel: "Drop a portrait or photo here",
    supported: "PNG, JPG, WebP, GIF, BMP",
    controls: [
      { label: "Photo contrast", value: "Balanced", helper: "Avoid washed-out images." },
      { label: "Panel width", value: "100 mm", helper: "Match your printer bed." },
      { label: "Orientation", value: "Vertical", helper: "Recommended for many lithophanes." },
    ],
    steps: ["Upload a photo.", "Check contrast and size.", "Create the lithophane STL."],
    pains: ["Safer than promising photo-to-3D reconstruction.", "Focuses on a real 3D printing use case.", "Helps users avoid poor photo choices."],
    outputFacts: [
      { label: "Input", value: "Photo" },
      { label: "Output", value: "Backlit STL panel" },
      { label: "Best for", value: "Backlit prints" },
    ],
    limit: "This creates a lithophane panel, not a full 3D object model.",
    related: [
      { label: "Backlit Photo Panel", href: "/lithophane-generator" },
      { label: "3D Print Photo", href: "/3d-print-photo" },
      { label: "Image Contrast Guide", href: "/image-contrast-guide" },
    ],
    faq: [
      { q: "Is this photo to 3D?", a: "It is photo to lithophane, a realistic 3D printing task for a single image." },
      { q: "Can I use portraits?", a: "Yes, portraits can work well when contrast and lighting are clear." },
    ],
  },
  {
    slug: "3d-print-photo",
    navLabel: "3D Print Photo",
    eyebrow: "Photo print planning tool",
    title: "3D Print Photo",
    description: "Choose whether a photo should become a lithophane, relief STL, or another image-to-STL workflow before spending time on the wrong print path.",
    promise: "Answer a few print questions and get the right tool path.",
    primaryCta: "Check Photo Path",
    secondaryCta: "Open Lithophane Tool",
    uploadLabel: "Optional: upload photo for planning",
    supported: "No upload required for basic guidance",
    controls: [
      { label: "Goal", value: "Backlit photo", helper: "Use lithophane for light-based prints." },
      { label: "Printer", value: "FDM", helper: "FDM works well for larger lithophanes." },
      { label: "Detail level", value: "Medium", helper: "Higher detail may need smaller layers." },
    ],
    steps: ["Pick your photo goal.", "Review print setup suggestions.", "Open the matching generator."],
    pains: ["Prevents users from choosing the wrong workflow.", "Connects photo intent to real print settings.", "Adds value beyond a static article."],
    outputFacts: [
      { label: "Decision", value: "Lithophane or relief" },
      { label: "Output", value: "Tool recommendation" },
      { label: "Next step", value: "Generate STL" },
    ],
    limit: "These are general print suggestions, not guaranteed printer settings.",
    related: [
      { label: "Backlit Photo Panel", href: "/lithophane-generator" },
      { label: "Photo to Backlit Panel", href: "/photo-to-lithophane" },
      { label: "Print Settings Checker", href: "/print-settings-checker" },
    ],
    faq: [
      { q: "Can I 3D print a photo?", a: "Yes, usually as a lithophane or relief rather than a full object model." },
      { q: "Which path should I choose?", a: "Use lithophane for backlit photos and relief STL for raised surface art." },
    ],
  },
  {
    slug: "jpg-to-stl",
    navLabel: "JPG entry",
    eyebrow: "Format-specific starting point",
    title: "JPG to STL Converter",
    description: "A JPG/photo-focused image-to-STL entry for relief prints, photo cleanup decisions, and lithophane alternatives.",
    promise: "Use this page for common camera or downloaded JPG files, with clear guidance that ordinary photos usually work better as lithophanes than raised reliefs.",
    primaryCta: "Upload JPG",
    secondaryCta: "Generate STL",
    uploadLabel: "Drop a JPG, PNG, WebP, GIF, or BMP image here",
    supported: "JPG, PNG, WebP, GIF, BMP",
    controls: [
      { label: "Contrast boost", value: "52%", helper: "Helps photos produce clearer relief." },
      { label: "Noise cleanup", value: "Medium", helper: "Reduce messy relief artifacts." },
      { label: "Relief depth", value: "36%", helper: "Keep photo relief printable." },
    ],
    steps: ["Upload a JPG-style image.", "Clean contrast and noise.", "Generate a relief STL."],
    pains: ["Converts common browser-readable image formats in one place.", "Gives photo users a clearer path.", "Keeps output framed as relief STL."],
    outputFacts: [
      { label: "Input", value: "JPG/PNG/WebP/GIF/BMP" },
      { label: "Output", value: "Relief STL + preview" },
      { label: "Status", value: "Live browser normalization" },
    ],
    limit: "Non-PNG images are normalized to PNG in the browser before STL generation. STL output remains single-material geometry.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "JPEG to STL", href: "/jpeg-to-stl" },
      { label: "Photo to Backlit Panel", href: "/photo-to-lithophane" },
      { label: "Contrast Guide", href: "/image-contrast-guide" },
    ],
    faq: [
      { q: "How does JPG and WebP input work?", a: "The browser normalizes supported non-PNG images to PNG first, then sends the image to the STL relief generator." },
      { q: "Should I use JPG to STL or lithophane?", a: "Use lithophane for portraits and photos with subtle shading. Use JPG relief when the subject has strong contrast and clear edges." },
      { q: "Why can photo relief look noisy?", a: "JPG photos contain shadows, texture, compression artifacts, and backgrounds. Those values can become unwanted bumps in a relief STL." },
      { q: "Is this photo reconstruction?", a: "No. It prepares a relief or lithophane-style STL path, not a full 3D reconstructed object." },
    ],
  },
  {
    slug: "jpeg-to-stl",
    navLabel: "JPEG to STL",
    eyebrow: "JPEG image conversion path",
    title: "JPEG to STL Converter",
    description: "Convert JPEG images into relief-style STL outputs with the same image-fit warnings, preview, and photo-to-lithophane routing used by the main image converter.",
    promise: "A JPEG-specific landing page for common photo uploads without promising full AI object reconstruction.",
    primaryCta: "Upload JPEG",
    secondaryCta: "Preview STL",
    uploadLabel: "Drop a JPEG, JPG, PNG, WebP, GIF, or BMP image here",
    supported: "JPEG, JPG, PNG, WebP, GIF, BMP",
    controls: [
      { label: "Photo contrast", value: "Medium", helper: "Clearer contrast improves relief separation." },
      { label: "Noise warning", value: "On", helper: "Busy JPEG texture may be routed away from clean extrude." },
      { label: "Recommended path", value: "Relief or lithophane", helper: "Most JPEG photos are safer as lithophanes than logo-style extrusion." },
    ],
    steps: ["Upload a JPEG image.", "Check whether it fits relief or lithophane.", "Generate and preview the STL."],
    pains: ["Matches users who search JPEG instead of JPG.", "Explains why normal photos can fail as clean STL.", "Keeps the converter self-contained on this page."],
    outputFacts: [
      { label: "Input", value: "JPEG/JPG" },
      { label: "Output", value: "Relief or lithophane STL" },
      { label: "Preview", value: "Built-in viewer" },
    ],
    limit: "JPEG images are normalized before generation; compression noise and backgrounds can still create poor relief surfaces.",
    related: [
      { label: "JPG to STL", href: "/jpg-to-stl" },
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Photo to Backlit Panel", href: "/photo-to-lithophane" },
    ],
    faq: [
      { q: "Is JPEG different from JPG here?", a: "No. JPEG and JPG are treated as the same image family; this page exists because users search both terms." },
      { q: "Can a JPEG photo become a full 3D object?", a: "No. A single JPEG can become relief, lithophane, or heightmap-style geometry, not a full reconstructed object." },
    ],
  },
  {
    slug: "pic-to-stl",
    navLabel: "Pic to STL",
    eyebrow: "Broad picture-to-STL entry",
    title: "Pic to STL Converter",
    description: "A beginner-friendly picture-to-STL page that routes ordinary images toward realistic relief, logo, lithophane, or heightmap workflows before generating STL output.",
    promise: "Use this page when you only know you have a picture and need the safest STL workflow recommendation.",
    primaryCta: "Upload Picture",
    secondaryCta: "Check Best Mode",
    uploadLabel: "Drop a picture to check the best STL workflow",
    supported: "PNG, JPG, JPEG, WebP, GIF, BMP",
    controls: [
      { label: "Image type", value: "Auto check", helper: "The converter checks whether the picture is a logo, photo, or heightmap-like source." },
      { label: "Best path", value: "Recommended", helper: "Avoid clean extrude when the source is too complex." },
      { label: "Download", value: "STL", helper: "Preview before downloading and slicer-check before printing." },
    ],
    steps: ["Upload a picture.", "Review the recommended STL workflow.", "Generate only when the image fits the selected mode."],
    pains: ["Captures broad picture-to-STL search intent.", "Reduces failed uploads from complex photos.", "Points beginners to realistic print outputs."],
    outputFacts: [
      { label: "Input", value: "Picture file" },
      { label: "Decision", value: "Logo/relief/lithophane/heightmap" },
      { label: "Output", value: "STL when suitable" },
    ],
    limit: "This is a workflow router for picture-to-STL relief outputs, not a magic AI 3D object generator.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "JPG to STL", href: "/jpg-to-stl" },
    ],
    faq: [
      { q: "What is the best picture for STL conversion?", a: "Simple icons, clean logos, silhouettes, or high-contrast artwork work best for relief STL. Photos usually need lithophane-style output." },
      { q: "Why does the page warn before generating?", a: "The warning prevents complex pictures from producing unusable clean-extrude STL shapes." },
    ],
  },
  {
    slug: "photo-to-stl",
    navLabel: "Photo to STL",
    eyebrow: "Photo relief workflow",
    title: "Photo to STL Converter",
    description: "Turn suitable photos into raised relief STL panels with realistic print guidance, smoothing defaults, and lithophane routing when a backlit panel is the better choice.",
    promise: "Use this page for photos that should become a raised display panel, not a full reconstructed 3D object.",
    primaryCta: "Upload Photo",
    secondaryCta: "Preview Relief",
    uploadLabel: "Drop a photo for raised relief STL",
    supported: "PNG, JPG, JPEG, WebP, GIF, BMP",
    controls: [
      { label: "Subject clarity", value: "Important", helper: "Clear foregrounds produce cleaner relief." },
      { label: "Relief smoothing", value: "High", helper: "Reduces photo texture noise." },
      { label: "Backlit option", value: "Lithophane", helper: "Use photo panel mode when the print needs light." },
    ],
    steps: ["Upload a clear photo.", "Review whether relief or lithophane is safer.", "Generate a raised photo STL panel."],
    pains: ["Captures photo-to-STL search intent with a realistic output.", "Prevents normal photos from being promised as full 3D objects.", "Routes portraits and tonal images toward lithophanes when needed."],
    outputFacts: [
      { label: "Input", value: "Photo" },
      { label: "Output", value: "Raised relief STL" },
      { label: "Alternative", value: "Backlit lithophane" },
    ],
    limit: "Photo to STL creates a front-facing relief panel from one image. It does not infer hidden backside geometry or produce a full sculpted 3D object.",
    related: [
      { label: "JPG to STL", href: "/jpg-to-stl" },
      { label: "Backlit Photo Panel", href: "/lithophane-generator" },
      { label: "Image Contrast Guide", href: "/image-contrast-guide" },
    ],
    faq: [
      { q: "Can a photo become an STL?", a: "Yes, as a relief or lithophane-style STL when the photo has a clear subject and usable contrast." },
      { q: "Is photo to STL the same as AI 3D reconstruction?", a: "No. This page creates a raised surface from a single photo, not a full 3D object with a back side." },
      { q: "When should I use lithophane instead?", a: "Use a lithophane when the final print will be backlit or when the photo relies on smooth tonal detail." },
    ],
  },
  {
    slug: "photo-relief-generator",
    navLabel: "Photo Relief",
    eyebrow: "Portrait relief generator",
    title: "Photo Relief Generator",
    description: "Generate raised photo relief STL panels from portraits, pet photos, memorial plaques, and display images with crop, background cleanup, and smoothing defaults.",
    promise: "Best for photos with one clear subject that should become a front-facing raised relief panel.",
    primaryCta: "Upload Photo",
    secondaryCta: "Preview Relief",
    uploadLabel: "Drop a portrait or subject photo here",
    supported: "PNG, JPG, JPEG, WebP, GIF, BMP",
    controls: [
      { label: "Subject focus", value: "Auto crop", helper: "Sparse side margins are trimmed so the portrait stays large." },
      { label: "Background", value: "Flattened", helper: "Busy texture is suppressed before STL generation." },
      { label: "Smoothing", value: "High", helper: "Photo relief needs softer height transitions than logos." },
    ],
    steps: ["Upload a photo with a clear foreground subject.", "Use the photo relief check to apply smoother settings if needed.", "Preview and download the raised relief STL."],
    pains: ["Keeps portrait users away from logo extrusion.", "Explains why busy backgrounds become noisy relief.", "Gives memorial and display plaque users a dedicated page."],
    outputFacts: [
      { label: "Best for", value: "Portraits and plaques" },
      { label: "Output", value: "Photo relief STL" },
      { label: "Processing", value: "Subject crop + background flatten" },
    ],
    limit: "A photo relief is a raised front surface, not a full 3D sculpture or AI reconstruction.",
    related: [
      { label: "Photo to STL", href: "/photo-to-stl" },
      { label: "Lithophane Generator", href: "/lithophane-generator" },
      { label: "Why Image to STL Looks Bad", href: "/why-your-image-to-stl-looks-bad" },
    ],
    faq: [
      { q: "What photos work best for relief?", a: "Portraits, pets, and single-subject images with clear contrast usually work better than full landscapes." },
      { q: "Why flatten the background?", a: "Background texture can become unwanted bumps in STL geometry, so this page uses smoother photo-relief defaults." },
    ],
  },
  {
    slug: "stl-relief-generator",
    navLabel: "STL Relief",
    eyebrow: "Raised surface STL maker",
    title: "STL Relief Generator",
    description: "Create printable relief STL panels from high-contrast artwork, photos, sketches, or grayscale images with scale, depth, base thickness, and smoothing controls.",
    promise: "A general relief STL page for users who know they want a raised surface rather than a clean logo badge or lithophane.",
    primaryCta: "Generate Relief STL",
    secondaryCta: "Tune Relief",
    uploadLabel: "Drop image artwork for relief STL",
    supported: "PNG, JPG, JPEG, WebP, GIF, BMP",
    controls: [
      { label: "Relief depth", value: "2.4 mm", helper: "Controls the raised surface height." },
      { label: "Base", value: "Printable slab", helper: "Adds support under the relief." },
      { label: "Smoothing", value: "Medium", helper: "Balances detail and printability." },
    ],
    steps: ["Upload artwork or a high-contrast photo.", "Set relief depth and base thickness.", "Preview the printable raised surface STL."],
    pains: ["Matches users searching for relief STL specifically.", "Keeps full 3D expectations separate from raised-surface output.", "Works as the hub for relief-specific internal links."],
    outputFacts: [
      { label: "Type", value: "Raised surface" },
      { label: "Output", value: "Relief STL" },
      { label: "Best for", value: "Panels, plaques, surface art" },
    ],
    limit: "Relief STL maps image values to height; it does not reconstruct hidden sides or backs of objects.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Photo Relief Generator", href: "/photo-relief-generator" },
      { label: "Heightmap to STL", href: "/heightmap-to-stl" },
    ],
    faq: [
      { q: "What is a relief STL?", a: "A relief STL is a raised or recessed surface generated from image brightness, contrast, or mask shape." },
      { q: "Is relief better than lithophane?", a: "Use relief for visible raised surfaces and lithophane for backlit photo detail." },
    ],
  },
  {
    slug: "svg-to-stl",
    navLabel: "SVG to STL",
    eyebrow: "Vector logo path",
    title: "SVG to STL Converter",
    description: "Use SVG or vector-style logo artwork as a starting point for clean raised STL badges, signs, stamps, and maker labels.",
    promise: "Best for vector logos and simple SVG-like artwork that should become solid raised geometry.",
    primaryCta: "Upload SVG or PNG",
    secondaryCta: "Preview Badge",
    uploadLabel: "Drop SVG-style logo artwork here",
    supported: "SVG or PNG; simple paths recommended",
    controls: [
      { label: "Vector intent", value: "Logo badge", helper: "Crisp vector shapes are routed to logo extrusion." },
      { label: "Smoothing", value: "Off", helper: "Preserve clean edges for signs and badges." },
      { label: "Bevel", value: "On", helper: "Softens the raised edge for a finished look." },
    ],
    steps: ["Upload an SVG or exported transparent PNG.", "Use logo badge settings for clean edges.", "Preview and download the raised STL."],
    pains: ["Captures vector-to-STL intent without claiming full CAD parsing for every SVG feature.", "Routes simple paths to the clean logo workflow.", "Explains that complex SVG effects should be flattened first."],
    outputFacts: [
      { label: "Input", value: "SVG/PNG logo" },
      { label: "Output", value: "Raised badge STL" },
      { label: "Best for", value: "Vector marks" },
    ],
    limit: "For now, complex SVG filters, gradients, and nested effects should be exported as a clean transparent PNG before conversion.",
    related: [
      { label: "Logo to STL", href: "/logo-to-stl" },
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Icon to STL", href: "/icon-to-stl" },
    ],
    faq: [
      { q: "Can I upload SVG files?", a: "The page accepts SVG-style logo workflows, but simple exported transparent PNGs remain the safest path for clean STL output." },
      { q: "What SVGs work best?", a: "Flat vector marks with closed shapes, thick strokes, and no tiny details work best." },
    ],
  },
  {
    slug: "icon-to-stl",
    navLabel: "Icon to STL",
    eyebrow: "Icon badge workflow",
    title: "Icon to STL Converter",
    description: "Turn app icons, simple UI symbols, stickers, and transparent icon PNGs into small raised STL badges with clean single-height geometry.",
    promise: "Use this page for icons and symbols that should print as a compact badge or stamp.",
    primaryCta: "Upload Icon",
    secondaryCta: "Preview Icon STL",
    uploadLabel: "Drop a transparent icon PNG here",
    supported: "PNG, SVG-style artwork, WebP",
    controls: [
      { label: "Icon style", value: "Single-height", helper: "Avoids color noise on flat icon art." },
      { label: "Base", value: "Optional badge", helper: "Keeps separated icon pieces printable." },
      { label: "Detail", value: "High", helper: "Preserves crisp symbol edges." },
    ],
    steps: ["Upload a simple icon or sticker image.", "Keep the icon in clean badge mode.", "Download the printable STL."],
    pains: ["Icons need different defaults than photos.", "Transparent backgrounds become clean empty space.", "Single-height geometry prevents colored icon noise."],
    outputFacts: [
      { label: "Best for", value: "Icons and stickers" },
      { label: "Output", value: "Clean badge STL" },
      { label: "Height", value: "Single raised level" },
    ],
    limit: "Tiny icon details, thin strokes, and anti-aliased edges may need cleanup before printing.",
    related: [
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Logo to STL", href: "/logo-to-stl" },
      { label: "Silhouette to STL", href: "/silhouette-to-stl" },
    ],
    faq: [
      { q: "Can icons become STL files?", a: "Yes. Simple icons can become raised STL badges or stamps when their shapes are clear enough." },
      { q: "Why use single-height output?", a: "Flat icons often use color for meaning, but STL stores geometry, so single-height extrusion avoids unwanted bumps." },
    ],
  },
  {
    slug: "silhouette-to-stl",
    navLabel: "Silhouette to STL",
    eyebrow: "Outline and silhouette STL",
    title: "Silhouette to STL Converter",
    description: "Convert black silhouettes, cutout shapes, decals, and outline art into clean single-height STL badges or raised shapes for 3D printing.",
    promise: "Best for one-color silhouettes where the outline matters more than internal shading.",
    primaryCta: "Upload Silhouette",
    secondaryCta: "Preview Shape STL",
    uploadLabel: "Drop a black silhouette or transparent cutout here",
    supported: "PNG, JPG, WebP, SVG-style artwork",
    controls: [
      { label: "Threshold", value: "Strong", helper: "Separates the silhouette from background." },
      { label: "Height", value: "Single-level", helper: "Creates a solid raised shape." },
      { label: "Island cleanup", value: "On", helper: "Removes tiny stray dots." },
    ],
    steps: ["Upload a silhouette or cutout image.", "Use threshold and mask cleanup for one solid shape.", "Preview the raised STL before download."],
    pains: ["Silhouettes should not be treated as photos.", "Cuts empty background instead of making a square plate.", "Good for decals, signs, and simple cookie-cutter shapes."],
    outputFacts: [
      { label: "Input", value: "Silhouette" },
      { label: "Output", value: "Single-height STL" },
      { label: "Best for", value: "Outlines and cutouts" },
    ],
    limit: "Very thin silhouettes may break when printed; use thicker source art or add a base plate.",
    related: [
      { label: "Icon to STL", href: "/icon-to-stl" },
      { label: "Logo to STL", href: "/logo-to-stl" },
      { label: "Black and White Image to STL", href: "/black-and-white-image-to-stl" },
    ],
    faq: [
      { q: "What is silhouette to STL?", a: "It turns a clear one-color shape into raised STL geometry using mask-style extrusion." },
      { q: "Should I use this for portraits?", a: "Only if the portrait has already been simplified into a strong silhouette." },
    ],
  },
  {
    slug: "black-and-white-image-to-stl",
    navLabel: "B/W to STL",
    eyebrow: "Monochrome threshold workflow",
    title: "Black and White Image to STL Converter",
    description: "Convert black-and-white images, monochrome art, stamps, stencil graphics, and thresholded drawings into clean raised STL shapes.",
    promise: "Best for binary artwork where black and white should become raised versus empty geometry.",
    primaryCta: "Upload Black and White Image",
    secondaryCta: "Preview Threshold STL",
    uploadLabel: "Drop black-and-white artwork here",
    supported: "PNG, JPG, WebP, BMP",
    controls: [
      { label: "Threshold", value: "58%", helper: "Controls which pixels become raised geometry." },
      { label: "Mode", value: "Monochrome mask", helper: "Treats the source as binary art." },
      { label: "Cleanup", value: "Small islands removed", helper: "Reduces dots and speckle." },
    ],
    steps: ["Upload monochrome or thresholded art.", "Adjust threshold if needed.", "Generate a clean raised STL."],
    pains: ["Separates black-and-white intent from photo relief.", "Works for stamps, stencils, and line-art signs.", "Explains threshold before users print speckled noise."],
    outputFacts: [
      { label: "Input", value: "Black and white image" },
      { label: "Output", value: "Thresholded STL" },
      { label: "Best for", value: "Stamps and stencils" },
    ],
    limit: "Anti-aliased grayscale edges can still produce small artifacts; clean binary source art prints best.",
    related: [
      { label: "Silhouette to STL", href: "/silhouette-to-stl" },
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Logo to STL", href: "/logo-to-stl" },
    ],
    faq: [
      { q: "How does black and white image to STL work?", a: "The converter treats strong black/white contrast as a mask and turns the selected area into raised STL geometry." },
      { q: "Can grayscale photos use this page?", a: "Only if you want a hard threshold look. Photos usually work better as relief or lithophane." },
    ],
  },
  {
    slug: "text-to-3d",
    navLabel: "Text to 3D",
    eyebrow: "Planned AI text-to-3D path",
    title: "Text to 3D Model Generator",
    description: "Plan a text-to-3D workflow while using current relief, logo, and image-to-STL tools for printable text plaques, signs, and raised lettering today.",
    promise: "Current live output is relief-style STL from images; true prompt-to-3D generation is planned for the AI 3D layer.",
    primaryCta: "Use Current STL Tools",
    secondaryCta: "View AI Roadmap",
    uploadLabel: "Optional: upload text artwork or a logo image",
    supported: "PNG, JPG, WebP, SVG-style artwork; text prompt generation planned",
    controls: [
      { label: "Live today", value: "Text artwork relief", helper: "Upload rendered text or logo art for STL output." },
      { label: "Planned", value: "Prompt to GLB/STL", helper: "AI text-to-3D needs a dedicated generation backend." },
      { label: "Best current path", value: "Logo/sign tools", helper: "Raised lettering prints better from clean artwork." },
    ],
    steps: ["Upload rendered text artwork for a current relief STL.", "Use logo/sign defaults for raised lettering.", "Return when AI text-to-3D generation is available."],
    pains: ["Captures text-to-3D demand honestly.", "Routes current users to working sign and logo relief tools.", "Creates the future page for prompt-based 3D generation."],
    outputFacts: [
      { label: "Current", value: "Relief from text artwork" },
      { label: "Planned", value: "AI text to 3D" },
      { label: "Status", value: "Roadmap" },
    ],
    limit: "Prompt-based text-to-3D generation is not live yet. Current tools need an image upload or rendered text artwork.",
    related: [
      { label: "AI Image to 3D", href: "/ai-image-to-3d" },
      { label: "Logo to STL", href: "/logo-to-stl" },
      { label: "Image to STL", href: "/image-to-stl" },
    ],
    faq: [
      { q: "Is text to 3D live?", a: "Not as prompt-based AI generation. Current live tools can turn rendered text artwork into relief STL." },
      { q: "What should I use for raised lettering now?", a: "Use logo or PNG-to-STL workflows with clean high-contrast text artwork." },
    ],
  },
  {
    slug: "ai-image-to-3d",
    navLabel: "AI 3D Workspace",
    eyebrow: "AI 3D task workspace",
    title: "AI Image to 3D Workspace",
    description: "Upload one image, check whether full AI 3D is available, and keep printable STL fallback routes visible when the provider is not configured.",
    promise: "Use this as a single AI 3D / STL decision workspace: real provider task when available, honest fallback to structured artwork, relief, lithophane, logo, or heightmap STL when it is not.",
    primaryCta: "Open AI 3D workspace",
    secondaryCta: "Use Image to STL",
    uploadLabel: "Drop an image to choose the right 3D workflow",
    supported: "PNG, JPG, WebP, GIF, BMP",
    controls: [
      { label: "Provider", value: "Requires config", helper: "Full AI 3D appears only when the external provider key is configured." },
      { label: "Fallback", value: "Structured STL", helper: "Complex artwork becomes layered 2.5D STL, not fake full 3D." },
      { label: "Output", value: "Task or STL", helper: "Provider tasks can return model links; fallback routes generate printable STL." },
    ],
    steps: ["Upload a single image.", "Check provider availability and image fit.", "Start AI 3D if configured, or route to printable STL fallback."],
    pains: ["Avoids pretending every image becomes true full 3D.", "Keeps Meshy/AI provider status visible instead of hiding unavailable states.", "Routes logos, photos, sketches, and heightmaps into the safer current STL workflows."],
    outputFacts: [
      { label: "Provider", value: "Config required" },
      { label: "Fallback", value: "Structured STL" },
      { label: "Truth", value: "No fake full 3D" },
    ],
    limit: "Full AI 3D depends on an external provider configuration. Without it, use structured artwork, relief, lithophane, logo, or heightmap STL workflows.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Logo to STL", href: "/logo-to-stl" },
      { label: "Photo Panel", href: "/lithophane-generator" },
      { label: "Depth Map", href: "/heightmap-to-stl" },
    ],
    faq: [
      { q: "Is full AI 3D always available here?", a: "No. Full AI 3D requires an external provider configuration. When it is unavailable, the page should say so and keep printable STL fallback paths active." },
      { q: "What happens without the provider key?", a: "The workspace still works as a router for structured artwork, logo, relief, lithophane, and heightmap STL outputs." },
      { q: "Is structured artwork true full 3D?", a: "No. It is a printable 2.5D layered STL route for complex drawings and artwork." },
    ],
    converter: {
      mode: "structured",
      accept: "image/png,image/jpeg,image/webp,image/gif,image/bmp",
      widthMm: 100,
      depth: 2.4,
      baseMm: 1.2,
      threshold: 30,
      smoothing: 15,
      detail: 320,
      helper: "Provider-based AI 3D requires configuration. Until it is available, this workspace routes complex artwork to structured STL and keeps relief, lithophane, logo, and heightmap paths one click away.",
      preview: "Upload an image to check provider availability and generate a structured printable STL fallback when full AI 3D is not configured.",
      filename: "ai-image-to-3d-structured-fallback.stl",
    },
  },
  {
    slug: "logo-to-stl",
    navLabel: "Logo to STL",
    eyebrow: "Logo relief tool",
    title: "Logo to STL Converter",
    description: "Turn simple logos, icons, and transparent PNG artwork into raised relief STL files for 3D printed badges, signs, stamps, and maker labels.",
    promise: "Use edge-friendly settings for badges, signs, and maker projects.",
    primaryCta: "Upload Logo",
    secondaryCta: "Preview Relief",
    uploadLabel: "Drop a high-contrast logo here",
    supported: "PNG or SVG",
    controls: [
      { label: "Edge sharpness", value: "High", helper: "Logos usually need crisp edges." },
      { label: "Base thickness", value: "1.2 mm", helper: "Adds a printable backing." },
      { label: "Relief height", value: "2.4 mm", helper: "Controls raised logo height." },
    ],
    steps: ["Upload a logo.", "Set base and relief height.", "Download a logo STL."],
    pains: ["Better for logos than a generic converter.", "Guides users toward simple high-contrast artwork.", "Useful for badges, plaques, and signs."],
    outputFacts: [
      { label: "Best for", value: "Logos/icons" },
      { label: "Output", value: "Raised STL" },
      { label: "Print type", value: "Badge/sign" },
    ],
    limit: "Complex or low-contrast logos may need cleanup before conversion.",
    related: [
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Heightmap to STL", href: "/heightmap-to-stl" },
    ],
    faq: [
      { q: "What logo works best?", a: "Flat, high-contrast logos with clean edges produce the best relief." },
      { q: "Can it make a 3D mascot?", a: "No. It makes raised logo relief, not a sculpted 3D character." },
    ],
  },
  {
    slug: "heightmap-to-stl",
    navLabel: "Heightmap to STL",
    eyebrow: "Heightmap relief builder",
    title: "Heightmap to STL Converter",
    description: "Convert grayscale heightmaps and brightness maps into relief-style STL terrain, surface tiles, and printable depth-mapped panels with smoothing controls.",
    promise: "Map light and dark values into printable height for terrain or surface relief.",
    primaryCta: "Upload Heightmap",
    secondaryCta: "Tune Heights",
    uploadLabel: "Drop a grayscale heightmap here",
    supported: "PNG grayscale recommended",
    controls: [
      { label: "Min height", value: "0.4 mm", helper: "Keeps the surface printable." },
      { label: "Max height", value: "8 mm", helper: "Controls the tallest points." },
      { label: "Smoothing", value: "Low", helper: "Reduce jagged steps when needed." },
    ],
    steps: ["Upload a heightmap.", "Set min and max height.", "Export an STL surface."],
    pains: ["Serves technical users who already know heightmaps.", "Clarifies brightness-to-height behavior.", "Useful for terrain and surface relief."],
    outputFacts: [
      { label: "Input", value: "Heightmap PNG" },
      { label: "Output", value: "Surface STL" },
      { label: "Mapping", value: "Brightness -> height" },
    ],
    limit: "Heightmap STL is a relief surface, not a full enclosed CAD assembly unless implementation adds walls/base.",
    related: [
      { label: "PNG to STL", href: "/png-to-stl" },
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Print Settings", href: "/print-settings-checker" },
    ],
    faq: [
      { q: "What is a heightmap?", a: "A grayscale image where brightness represents surface height." },
      { q: "Can it make terrain?", a: "It can create relief-style terrain surfaces when the heightmap is suitable." },
    ],
  },
  {
    slug: "2d-image-to-3d-model",
    navLabel: "2D to 3D Relief",
    eyebrow: "Safe 2D-to-3D page",
    title: "2D Image to 3D Model",
    description: "Turn 2D images into relief-style 3D printable STL files while setting realistic expectations about single-image depth and full 3D reconstruction limits.",
    promise: "A practical 2D-to-3D workflow without claiming full object reconstruction.",
    primaryCta: "Upload 2D Image",
    secondaryCta: "See Limits",
    uploadLabel: "Drop a 2D image for relief conversion",
    supported: "PNG minimum",
    controls: [
      { label: "Relief mode", value: "Raised", helper: "Creates a printable raised surface." },
      { label: "Depth", value: "Medium", helper: "Avoid overly tall models." },
      { label: "Base", value: "On", helper: "Adds support for printing." },
    ],
    steps: ["Upload a 2D image.", "Choose relief settings.", "Download a 3D printable STL."],
    pains: ["Captures broad 2D-to-3D intent safely.", "Explains the limit before users expect magic.", "Routes users to realistic relief/lithophane tools."],
    outputFacts: [
      { label: "Claim", value: "Relief only" },
      { label: "Output", value: "STL" },
      { label: "Not", value: "CAD reconstruction" },
    ],
    limit: "This page creates relief-style models from 2D images, not full 3D reconstructed objects.",
    related: [
      { label: "Image to STL", href: "/image-to-stl" },
      { label: "Photo to Backlit Panel", href: "/photo-to-lithophane" },
      { label: "FAQ", href: "/faq" },
    ],
    faq: [
      { q: "Why call it 2D image to 3D model?", a: "Because users search that way, but the page clearly explains the realistic relief-style output." },
      { q: "Will it reconstruct the back side?", a: "No. A single 2D image does not contain full object geometry." },
    ],
  },
];

type HelperPage = {
  slug: string;
  title: string;
  description: string;
  cta: string;
  href: string;
  checks: string[];
  intent?: string;
  advisorKind?: "photo-path" | "jpg-gate" | "contrast" | "print-settings" | "logo" | "heightmap";
  sampleSlugs?: string[];
  faqs?: Array<{ q: string; a: string }>;
  steps?: Array<{ title: string; body: string }>;
};

export const helperPages: HelperPage[] = [
  {
    slug: "how-to-convert-image-to-stl",
    title: "How to Convert Image to STL for 3D Printing",
    description: "A step-by-step image-to-STL guide that explains when to use logo extrusion, photo relief, lithophane, or heightmap workflows before downloading an STL.",
    cta: "Open Image to STL",
    href: "/image-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=how_to_convert_image_to_stl",
    advisorKind: "contrast",
    intent: "Use this guide when you have a 2D image and need a realistic path to a printable STL without expecting full AI reconstruction.",
    sampleSlugs: ["universal-image-relief", "logo-badge-relief", "backlit-lithophane-panel"],
    checks: [
      "Upload a PNG, JPG, WebP, GIF, or BMP image with a clear subject.",
      "Choose logo mode for transparent marks, photo relief for raised panels, lithophane for backlit photos, and heightmap for real depth maps.",
      "Preview the STL before downloading so you can catch noisy backgrounds, tiny text, or weak contrast.",
      "Download the STL only after checking scale, relief height, and base thickness in the preview.",
    ],
    steps: [
      { title: "Upload the right source", body: "Start with the cleanest image available. Logos and silhouettes should be crisp, photos should have one clear subject, and heightmaps should be grayscale depth data." },
      { title: "Pick the workflow", body: "Do not treat every image the same. Use clean extrude for logos, relief for raised surfaces, lithophane for backlit photos, and heightmap mode for terrain data." },
      { title: "Preview and download", body: "Generate the STL, inspect the preview and metrics, then download the model for slicer checks and a small test print." },
    ],
    faqs: [
      { q: "Can any image be converted to STL?", a: "Most common image formats can be processed, but not every image makes a good STL. Simple high-contrast images are more reliable than noisy scenes." },
      { q: "Is this full 3D reconstruction?", a: "No. The live converter creates relief, logo badge, lithophane, or heightmap-style STL geometry from the image." },
    ],
  },
  {
    slug: "best-images-for-stl-conversion",
    title: "Best Images for STL Conversion",
    description: "Choose images that convert cleanly to STL by matching logos, photos, silhouettes, and heightmaps to the right 3D printing workflow.",
    cta: "Check Image Fit",
    href: "/image-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=best_images_for_stl_conversion",
    advisorKind: "contrast",
    intent: "Use this guide before uploading when you need to know whether logos, photos, icons, or heightmaps will create a clean printable STL.",
    sampleSlugs: ["logo-badge-relief", "pet-photo-relief", "terrain-heightmap-tile"],
    checks: [
      "Logos work best when they have flat colors, transparent backgrounds, and thick readable shapes.",
      "Photos work best when the subject is clear, cropped close, and separated from the background.",
      "Heightmaps must be grayscale depth maps, not ordinary landscape photos.",
      "Avoid tiny text, gradients, shadows, compression artifacts, and busy backgrounds when possible.",
    ],
    steps: [
      { title: "Match image type to workflow", body: "Use logos and icons for clean badges, photos for relief or lithophane, and real grayscale maps for heightmap STL." },
      { title: "Remove weak details", body: "Crop empty background, simplify tiny text, and increase contrast before generating geometry." },
      { title: "Run a preview", body: "Use the converter preview to see whether the image produces a printable result before downloading." },
    ],
    faqs: [
      { q: "What image is easiest to convert to STL?", a: "A simple transparent logo or black-and-white silhouette is usually easiest because the outline becomes clean geometry." },
      { q: "Are photos good for STL conversion?", a: "Photos can work as relief or lithophane panels, but they need clear subjects and usually need smoothing or background cleanup." },
    ],
  },
  {
    slug: "image-to-stl-vs-lithophane",
    title: "Image to STL vs Lithophane: Which Should You Choose?",
    description: "Compare raised image-to-STL reliefs with backlit lithophane panels so photos, logos, and grayscale artwork go to the right printable workflow.",
    cta: "Try Lithophane Generator",
    href: "/lithophane-generator?utm_source=seo_helper&utm_medium=internal&utm_campaign=image_to_stl_vs_lithophane",
    advisorKind: "photo-path",
    intent: "Use this comparison when a photo could become either a raised relief panel or a backlit lithophane and you need to choose the safer result.",
    sampleSlugs: ["universal-image-relief", "backlit-lithophane-panel", "portrait-lithophane-night-light"],
    checks: [
      "Choose image-to-STL relief when raised surface detail should be visible without light.",
      "Choose lithophane when the photo depends on smooth tones, faces, shadows, and backlighting.",
      "Choose logo extrusion for flat marks instead of either photo relief or lithophane.",
      "Preview both when the source is a portrait or memorial photo.",
    ],
    steps: [
      { title: "Decide how it will be viewed", body: "If the print will be viewed normally, use relief. If it will sit in front of a light, lithophane is usually better for photo detail." },
      { title: "Check the image content", body: "Logos and silhouettes need crisp geometry. Portraits and tonal photos often need thickness-based lithophane output." },
      { title: "Test a small crop", body: "For important gifts or memorial prints, test a small crop before printing the full panel." },
    ],
    faqs: [
      { q: "Is lithophane the same as image to STL?", a: "A lithophane is one type of image-to-STL output, but it uses thickness for backlit brightness instead of a normal raised relief surface." },
      { q: "Which is better for portraits?", a: "Lithophanes are often better for portraits because they preserve tonal detail when backlit." },
    ],
  },
  {
    slug: "why-your-image-to-stl-looks-bad",
    title: "Why Your Image to STL Looks Bad",
    description: "Diagnose common image-to-STL problems such as noisy backgrounds, low contrast, tiny text, over-smoothing, weak relief depth, and wrong workflow choice.",
    cta: "Try Photo to STL",
    href: "/photo-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=why_image_to_stl_looks_bad",
    advisorKind: "contrast",
    intent: "Use this guide when a generated STL looks muddy, noisy, too flat, too blocky, or unlike the source image.",
    sampleSlugs: ["pet-photo-relief", "logo-badge-relief", "backlit-lithophane-panel"],
    checks: [
      "Busy background texture can become unwanted bumps in photo relief.",
      "Low contrast makes the subject blend into the base instead of standing out.",
      "Too much smoothing can erase text and edges, while too little smoothing keeps JPEG noise.",
      "The wrong workflow can make a photo look bad as a logo badge or make a logo noisy as a photo relief.",
    ],
    steps: [
      { title: "Check the background", body: "Crop tightly and remove clutter. A background that looks harmless in a photo can become raised noise in STL geometry." },
      { title: "Check contrast and scale", body: "If the subject is small or low contrast, the relief will look weak. Use a clearer crop, larger width, or a dedicated photo relief workflow." },
      { title: "Switch workflow when needed", body: "Use logo mode for flat marks, photo relief for clear subjects, lithophane for tonal portraits, and heightmap mode only for depth maps." },
    ],
    faqs: [
      { q: "Why does my photo STL look noisy?", a: "Photo backgrounds, shadows, and compression artifacts can become geometry. Crop tighter, apply smoother settings, or try lithophane." },
      { q: "Why does my logo STL look messy?", a: "The logo may be treated like brightness relief instead of a clean mask. Use transparent PNG or logo-to-STL mode." },
    ],
  },
  {
    slug: "how-to-make-a-clean-logo-stl",
    title: "How to Make a Clean Logo STL",
    description: "Prepare transparent PNG logo artwork, choose base plate and bevel-friendly settings, and avoid tiny text or color noise when making a logo STL.",
    cta: "Open Logo to STL",
    href: "/logo-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=clean_logo_stl",
    advisorKind: "logo",
    intent: "Use this guide when you need a clean printable logo badge, sign, stamp, or maker label instead of a noisy color-based relief.",
    sampleSlugs: ["logo-badge-relief", "rubber-stamp-relief", "workshop-sign-plate"],
    checks: [
      "Use a transparent PNG or simple one-color artwork whenever possible.",
      "Keep a base plate when letters, holes, or separated islands need support.",
      "Use bevel or softened edges for a finished badge look, but avoid tiny fragile details.",
      "Remove gradients, shadows, low-resolution screenshots, and tiny taglines before conversion.",
    ],
    steps: [
      { title: "Prepare transparent PNG artwork", body: "Start with clean edges and enough resolution. Alpha transparency tells the converter what should be empty space." },
      { title: "Use logo badge settings", body: "Single-height extrusion, low smoothing, a reasonable base plate, and bevel-friendly relief height make cleaner logo STL files." },
      { title: "Inspect printability", body: "Check thin strokes, disconnected islands, and small text in the STL preview and slicer before printing." },
    ],
    faqs: [
      { q: "Why use transparent PNG for logo STL?", a: "Transparency gives a clean mask, so empty background does not become part of the raised model." },
      { q: "Should logo STL files use bevel?", a: "A light bevel can make badges and signs look more finished, but very small details may need simpler edges." },
    ],
  },
  {
    slug: "stl-file-for-3d-printing-guide",
    title: "STL File for 3D Printing Guide",
    description: "Understand what an STL file contains, how to check scale and thin details in a slicer, and why image-based STL files need preview before printing.",
    cta: "Open Print Settings Checker",
    href: "/print-settings-checker?utm_source=seo_helper&utm_medium=internal&utm_campaign=stl_file_guide",
    advisorKind: "print-settings",
    intent: "Use this guide after downloading a model or before slicing an image-generated STL for the first time.",
    sampleSlugs: ["logo-badge-relief", "portrait-lithophane-night-light", "terrain-heightmap-tile"],
    checks: [
      "STL stores triangles and geometry, not color, transparency, or the original image file.",
      "Open the STL in a slicer to check scale, orientation, base thickness, and thin walls.",
      "Use small test prints for relief, lithophane, and dense heightmap models.",
      "Watch for fragile text, steep walls, unsupported details, and overly thin panels.",
    ],
    steps: [
      { title: "Open the STL in a slicer", body: "Check physical dimensions, triangle-heavy areas, and whether the model lies flat or needs orientation changes." },
      { title: "Check fragile geometry", body: "Thin text, tiny islands, and tall relief can break or fail to print cleanly. Add a base or simplify the source when needed." },
      { title: "Print a test first", body: "A small crop or scaled test is the fastest way to catch contrast and printability problems." },
    ],
    faqs: [
      { q: "Does STL include image color?", a: "No. STL stores geometry only. Image colors are converted into shape, height, thickness, or mask decisions before export." },
      { q: "Why check STL scale before printing?", a: "Image-generated models can be too thin, too tall, or too small for your printer unless you verify dimensions in a slicer." },
    ],
  },
  {
    slug: "image-to-stl-settings",
    title: "Image to STL Settings Explained",
    description: "Understand image-to-STL settings such as width, relief height, base thickness, threshold, smoothing, detail level, inversion, and lithophane thickness.",
    cta: "Open Image to STL",
    href: "/image-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=image_to_stl_settings",
    advisorKind: "print-settings",
    intent: "Use this guide when the converter settings are confusing or when the first STL is too flat, too noisy, too large, or too fragile.",
    sampleSlugs: ["universal-image-relief", "logo-badge-relief", "heightmap-surface"],
    checks: [
      "Width controls physical model size, not image resolution.",
      "Relief height controls how tall raised details become above the base.",
      "Threshold separates raised versus empty areas for masks, logos, and black-and-white artwork.",
      "Smoothing reduces noise but can also soften text, edges, and fine line art.",
    ],
    steps: [
      { title: "Set size first", body: "Choose a printable width before tuning detail. A tiny model cannot preserve every pixel from a large image." },
      { title: "Tune height and base", body: "Use enough relief height to see detail, but keep base thickness and scale realistic for your printer." },
      { title: "Balance threshold and smoothing", body: "Use threshold for masks and smoothing for noisy photos. Re-preview after each major change." },
    ],
    faqs: [
      { q: "What does threshold do?", a: "Threshold decides which pixels become raised geometry in mask-style workflows such as logos, icons, silhouettes, and black-and-white images." },
      { q: "What smoothing should I use?", a: "Use low smoothing for logos and higher smoothing for photos with background texture or compression noise." },
    ],
  },
  {
    slug: "transparent-png-to-stl-guide",
    title: "Transparent PNG to STL Guide",
    description: "Use alpha transparency, clean masks, base plates, and logo badge settings to turn transparent PNG icons, stickers, and silhouettes into STL files.",
    cta: "Open PNG to STL",
    href: "/png-to-stl?utm_source=seo_helper&utm_medium=internal&utm_campaign=transparent_png_to_stl",
    advisorKind: "logo",
    intent: "Use this guide when the important part of a PNG is its alpha channel, transparent background, or sticker-like outline.",
    sampleSlugs: ["workshop-sign-plate", "cookie-cutter-outline", "keychain-name-tag"],
    checks: [
      "Alpha transparency should mark empty background, not become a square raised plate.",
      "Transparent PNG logos and icons work best with single-height badge extrusion.",
      "Use a base plate when separate pieces need to stay connected for printing.",
      "Avoid semi-transparent shadows and antialiased noise around the edge when possible.",
    ],
    steps: [
      { title: "Check the alpha channel", body: "Make sure the background is truly transparent. A white rectangle or screenshot background may become unwanted geometry." },
      { title: "Use PNG/logo mode", body: "Transparent PNG to STL should usually use mask-style extrusion rather than brightness-based photo relief." },
      { title: "Preview the badge", body: "Confirm that holes, letters, islands, and outer edges are connected or supported before downloading." },
    ],
    faqs: [
      { q: "Why is transparent PNG better for STL badges?", a: "The alpha channel tells the converter what is empty space, producing cleaner badge and sign geometry." },
      { q: "Can semi-transparent shadows cause problems?", a: "Yes. Soft shadows can create fuzzy edges or small artifacts. Flatten the design to a clean mask when possible." },
    ],
  },
  {
    slug: "photo-to-relief-stl-guide",
    title: "Photo to Relief STL Guide",
    description: "Turn portraits and clear subject photos into raised relief STL panels with background cleanup, smoothing, subject crop, and realistic photo-to-3D expectations.",
    cta: "Open Photo Relief Generator",
    href: "/photo-relief-generator?utm_source=seo_helper&utm_medium=internal&utm_campaign=photo_to_relief_stl",
    advisorKind: "photo-path",
    intent: "Use this guide when a photo should become a raised memorial plaque, portrait panel, pet relief, or display print rather than a backlit lithophane.",
    sampleSlugs: ["pet-photo-relief", "portrait-lithophane-night-light", "universal-image-relief"],
    checks: [
      "Choose photos with one clear portrait, pet, or subject instead of a full busy scene.",
      "Crop away excess background so the relief focuses on the subject.",
      "Use stronger smoothing to suppress background texture and JPEG noise.",
      "Try lithophane instead when smooth tonal detail matters more than raised surface texture.",
    ],
    steps: [
      { title: "Prepare the photo", body: "Use a clear portrait or subject crop. Background clutter, dark rooms, and tiny faces usually create weak relief STL." },
      { title: "Apply photo relief settings", body: "Use subject-focused crop, background flattening, and high smoothing so the model reads as a raised panel instead of noisy terrain." },
      { title: "Compare with lithophane", body: "If the photo depends on smooth shadows and face detail, a backlit lithophane may be the better STL output." },
    ],
    faqs: [
      { q: "Can a photo become relief STL?", a: "Yes, when the photo has a clear subject and enough contrast. It becomes a raised front-facing panel, not a full 3D sculpture." },
      { q: "Why does background matter for photo relief?", a: "Background texture can turn into unwanted height variation, so crop tightly or use smoothing before printing." },
    ],
  },
  {
    slug: "image-contrast-guide",
    title: "Image Contrast Guide",
    description: "Check whether an image has enough contrast, clean edges, and simple background separation before converting it into a relief, logo, or lithophane STL.",
    cta: "Try Image to STL",
    href: "/image-to-stl",
    advisorKind: "contrast",
    intent: "Use this guide before uploading when a relief STL looks muddy, letters merge together, or a lithophane preview loses the subject after grayscale conversion.",
    sampleSlugs: ["universal-relief", "logo-badge-relief", "backlit-lithophane-panel"],
    checks: [
      "Use clear edges between the subject and background.",
      "Avoid noisy backgrounds, compression artifacts, and shadows that can become unwanted bumps.",
      "Increase contrast for better relief separation before generating the STL.",
      "Keep the subject simple when possible; icons, silhouettes, and line art convert more predictably than busy photos.",
      "Crop out unused background so the model focuses on the printable subject.",
      "Preview grayscale values before choosing relief, logo, lithophane, or heightmap mode.",
    ],
    steps: [
      { title: "Separate the subject", body: "Start with a clear foreground and background. If the subject is hard to see in a small thumbnail, the STL relief will usually look noisy or flat." },
      { title: "Check grayscale contrast", body: "Brightness becomes height or thickness in many image-to-STL workflows. Convert the image mentally to grayscale and make sure important details still stand apart." },
      { title: "Choose the right output", body: "Use logo relief for crisp flat artwork, lithophane for photos with midtone detail, and heightmap mode only when the image is meant to encode depth." },
    ],
    faqs: [
      { q: "Why does contrast matter for image to STL?", a: "Contrast controls how clearly the converter can separate raised and recessed areas. Low-contrast images often create muddy relief with weak edges." },
      { q: "Should I edit the image before converting?", a: "Yes when the subject is noisy, dark, or surrounded by a busy background. Cropping, cleanup, and contrast adjustment can save failed prints." },
      { q: "Is high contrast always better?", a: "Not always. Logos and reliefs benefit from strong contrast, while lithophanes need balanced midtones so faces and shadows remain readable when backlit." },
    ],
  },
  {
    slug: "print-settings-checker",
    title: "Print Settings Checker",
    description: "Review practical slicer starting points for relief STL, logo badges, lithophane panels, and heightmap surfaces before wasting filament on a full print.",
    cta: "Check Print Settings",
    href: "/lithophane-generator",
    advisorKind: "print-settings",
    intent: "Use this checker after generating or previewing an STL to decide whether the model needs safer thickness, orientation, layer height, or a smaller test print.",
    sampleSlugs: ["backlit-lithophane-panel", "logo-badge-relief", "terrain-heightmap-tile"],
    checks: [
      "Use smaller layer heights for lithophanes and detailed relief surfaces.",
      "Keep thin lithophane panels within a safe minimum thickness before slicing.",
      "Print logo badges with a base plate when letters or icon islands are disconnected.",
      "Check orientation before printing tall relief or backlit photo panels.",
      "Run a small crop or scaled test before committing to a large panel.",
      "Review material and nozzle limits when tiny text, steep terrain, or thin edges appear in the STL.",
    ],
    steps: [
      { title: "Inspect the STL first", body: "Open the downloaded STL in your slicer and check dimensions, thin walls, disconnected islands, and whether the relief is too shallow or too tall." },
      { title: "Start with conservative settings", body: "Use practical layer height and thickness defaults before chasing maximum detail. Most failed image-to-STL prints come from fragile geometry or poor orientation." },
      { title: "Print a small test", body: "For photos, lithophanes, and dense heightmaps, print a crop or reduced-size sample to verify contrast, surface detail, and backlighting before a full plate." },
    ],
    faqs: [
      { q: "What layer height should I use for lithophanes?", a: "A smaller layer height usually preserves more photo detail. Start conservatively, then adjust based on your nozzle, material, and panel size." },
      { q: "Do relief STL files need supports?", a: "Many flat relief plates do not need supports, but tall raised details, steep terrain, or vertical lithophane panels may require orientation changes or support planning." },
      { q: "Why print a small test first?", a: "A small test reveals contrast, thin-wall, and scale problems before you spend hours and filament on the final STL print." },
    ],
  },
  {
    slug: "how-to-turn-logo-into-stl",
    title: "How to Turn a Logo into an STL for 3D Printing",
    description: "A practical logo-to-STL workflow for badges, signs, stamps, and maker labels, with checks for clean edges, relief height, and printable text.",
    cta: "Load logo badge preset",
    href: "/logo-to-stl?sample=logo-badge-relief&utm_source=seo_helper&utm_medium=internal&utm_campaign=logo_to_stl_guide",
    intent: "Users want to convert a logo into a printable raised badge or sign, not reconstruct a full 3D mascot.",
    advisorKind: "logo",
    sampleSlugs: ["logo-badge-relief", "rubber-stamp-relief", "workshop-sign-plate"],
    checks: [
      "Use a transparent PNG or simple black-on-white logo.",
      "Avoid thin serif text, tiny taglines, gradients, and mascot illustrations.",
      "Start around 80-120 mm width for signs and 2.0-2.4 mm relief height.",
      "Keep a base plate when the logo has disconnected islands or loose letters.",
    ],
    steps: [
      { title: "Prepare the artwork", body: "Use the highest-resolution logo you have. Transparent PNG works best because the converter can treat empty areas as background instead of raised geometry." },
      { title: "Choose badge-style settings", body: "Start with low smoothing, a printable base, and conservative relief height. Very tall relief can look dramatic but may print slowly or create fragile edges." },
      { title: "Inspect before printing", body: "Open the downloaded STL in a slicer. Check small letters, holes inside characters, and whether separated pieces need a shared base plate." },
    ],
    faqs: [
      { q: "Can I turn any logo into an STL?", a: "Simple, high-contrast logos work best. Gradients, shadows, tiny text, and detailed mascots often need cleanup before conversion." },
      { q: "Should a logo STL have a base plate?", a: "Usually yes for badges, signs, and stamps. A base keeps separated letters or icon islands connected and easier to print." },
    ],
  },
  {
    slug: "lithophane-image-guide",
    title: "Best Image for Lithophane 3D Prints",
    description: "Choose photos that work well as lithophanes, set thickness safely, and avoid washed-out or underexposed images before generating an STL.",
    cta: "Load lithophane preset",
    href: "/lithophane-generator?sample=backlit-lithophane-panel&utm_source=seo_helper&utm_medium=internal&utm_campaign=lithophane_image_guide",
    intent: "Users need to know whether a photo will become a readable backlit lithophane before wasting a print.",
    advisorKind: "photo-path",
    sampleSlugs: ["backlit-lithophane-panel", "portrait-lithophane-night-light"],
    checks: [
      "Pick photos with one clear subject and visible midtone contrast.",
      "Avoid blown-out highlights, very dark faces, and cluttered backgrounds.",
      "Use thin-to-thick ranges such as 0.8-3.0 mm or 0.8-3.2 mm for first tests.",
      "Print vertically or with enough support depending on panel size and slicer settings.",
    ],
    steps: [
      { title: "Check the subject", body: "Faces, pets, and simple scenes usually work better than busy landscapes. If the subject disappears in grayscale, it will likely disappear in the lithophane." },
      { title: "Set thickness range", body: "Thin areas transmit more light and thick areas block it. Start conservative so the panel is printable and still shows contrast when backlit." },
      { title: "Test with light", body: "A lithophane can look flat without backlight. Inspect the STL, slice it, and test a small crop before committing to a large panel." },
    ],
    faqs: [
      { q: "What kind of photo is best for a lithophane?", a: "A clear subject, balanced contrast, and simple background usually produce the most readable backlit print." },
      { q: "Should backlit panels be inverted?", a: "Often yes, because thickness controls brightness. The generator presets use lithophane-oriented inversion as a starting point." },
    ],
  },
  {
    slug: "heightmap-to-stl-terrain-guide",
    title: "Heightmap to STL Terrain Guide",
    description: "Turn grayscale heightmaps into printable terrain-style STL surfaces with practical width, max height, smoothing, and input checks.",
    cta: "Load terrain preset",
    href: "/heightmap-to-stl?sample=terrain-heightmap-tile&utm_source=seo_helper&utm_medium=internal&utm_campaign=heightmap_terrain_guide",
    intent: "Users with grayscale terrain or texture maps need brightness-to-height rules and safe print starting points.",
    advisorKind: "heightmap",
    sampleSlugs: ["heightmap-surface", "terrain-heightmap-tile"],
    checks: [
      "Use an actual grayscale heightmap where white means higher elevation and black means lower elevation.",
      "Do not use a normal color photo unless it was designed as height data.",
      "Start around 110-120 mm width and 5.5-6 mm max height for terrain tiles.",
      "Use low smoothing for readable terrain, more smoothing only when steps look too jagged.",
    ],
    steps: [
      { title: "Confirm the map type", body: "A heightmap is data, not just a landscape photo. Brightness values become geometry, so labels, colors, and shadows can create unwanted terrain." },
      { title: "Set safe height", body: "A max height around 5.5-6 mm gives visible terrain without creating cliffs that are hard to print at small scale." },
      { title: "Inspect the surface", body: "Check whether the terrain needs a base slab, lower smoothing, or a crop before printing the full tile." },
    ],
    faqs: [
      { q: "Can I use any terrain image as a heightmap?", a: "No. Use a grayscale heightmap or depth map. Regular photos and colored maps usually do not encode height cleanly." },
      { q: "What does white mean in a heightmap?", a: "In this workflow, brighter pixels become higher areas and darker pixels become lower areas." },
    ],
  },
  {
    slug: "best-lithophane-settings",
    title: "Best Photo Panel Settings for 3D Printing",
    description: "Choose safe lithophane thickness, image inversion, panel size, layer height, and test-print settings before downloading a photo-to-STL lithophane.",
    cta: "Open lithophane generator",
    href: "/lithophane-generator?sample=portrait-lithophane-night-light&utm_source=seo_helper&utm_medium=internal&utm_campaign=best_lithophane_settings",
    intent: "Users searching for lithophane settings usually have a photo ready and need practical numbers before they print.",
    advisorKind: "print-settings",
    sampleSlugs: ["backlit-lithophane-panel", "portrait-lithophane-night-light"],
    checks: [
      "Start with about 0.8 mm minimum thickness and 3.0-3.2 mm maximum thickness for a first test.",
      "Use image inversion when thicker areas should block more light and thin areas should glow brighter.",
      "Keep the subject simple and crop tightly so faces or pets stay readable when backlit.",
      "Print a small crop before committing to a full portrait, gift panel, or night-light insert.",
    ],
    steps: [
      { title: "Prepare the photo", body: "Pick a clear subject with visible midtones. Very dark faces, blown highlights, and cluttered backgrounds usually make weak lithophanes." },
      { title: "Set thickness first", body: "Thickness controls brightness. A conservative 0.8-3.2 mm range is easier to slice and test than extreme thin or thick settings." },
      { title: "Validate with a test print", body: "Download the STL, slice a small crop, and check it with a light source before printing the final panel." },
    ],
    faqs: [
      { q: "What thickness is best for lithophanes?", a: "A practical first range is about 0.8 mm minimum and 3.0-3.2 mm maximum, then adjust for your filament, light source, and printer." },
      { q: "Should I invert a lithophane image?", a: "Usually yes. In lithophanes, geometry thickness controls how much light passes through, so inversion often makes the final backlit image read correctly." },
      { q: "What layer height should I use?", a: "Use a smaller layer height for more detail, then verify with a small test because printer, nozzle, and panel size matter." },
    ],
  },
  {
    slug: "image-to-stl-relief-settings",
    title: "Image to STL Relief Settings for 3D Printing",
    description: "Pick practical relief depth, base thickness, image contrast, smoothing, and width settings when turning images, icons, and line art into STL files.",
    cta: "Open image to STL converter",
    href: "/image-to-stl?sample=universal-image-relief&utm_source=seo_helper&utm_medium=internal&utm_campaign=image_to_stl_relief_settings",
    intent: "Users with an image often need starting settings that make the STL printable instead of noisy, fragile, or too flat.",
    advisorKind: "contrast",
    sampleSlugs: ["universal-image-relief", "coin-relief-medallion", "pet-photo-relief"],
    checks: [
      "Use strong subject-background contrast before raising brightness into geometry.",
      "Start with moderate relief depth rather than a very tall surface that creates fragile details.",
      "Keep a base plate when letters, islands, or icon parts would otherwise become disconnected.",
      "Use smoothing carefully: too little can look jagged, while too much can erase text and edges.",
    ],
    steps: [
      { title: "Choose the right image", body: "Icons, line art, silhouettes, and simple high-contrast photos make cleaner relief STL files than busy scenes or low-contrast screenshots." },
      { title: "Start with safe geometry", body: "Set a printable width, moderate relief height, and base thickness before chasing maximum detail. The goal is a clean first STL, not the tallest possible surface." },
      { title: "Inspect before download", body: "Check whether small text merged, edges became noisy, or large flat areas need cropping before using the STL for a full print." },
    ],
    faqs: [
      { q: "What relief depth should I start with?", a: "Start moderate, then raise it only if the preview looks too flat. Very tall relief can be slow to print and may make thin details fragile." },
      { q: "Do I need a base plate?", a: "Use a base plate for logos, text, badges, signs, and any design with separated islands so the print stays connected." },
      { q: "Can a normal photo become a relief STL?", a: "Sometimes, but high-contrast subjects work best. Many photos are better as lithophanes instead of raised relief." },
    ],
  },
  {
    slug: "ai-image-to-3d-roadmap",
    title: "AI Image to 3D Roadmap",
    description: "Plan the future AI image-to-3D experience while keeping the live relief, logo, lithophane, and heightmap tools as the real printable path today.",
    cta: "Open AI 3D roadmap",
    href: "/ai-image-to-3d?utm_source=seo_helper&utm_medium=internal&utm_campaign=ai_image_to_3d_roadmap",
    intent: "Use this page when you want to understand the future AI product structure without mistaking it for an already live full 3D generator.",
    advisorKind: "photo-path",
    sampleSlugs: ["universal-image-relief", "backlit-lithophane-panel", "logo-badge-relief"],
    checks: [
      "The live product today is still relief-first and STL-first.",
      "GLB preview, credits, saved creations, and history belong in a future account flow.",
      "Batch and API access should be introduced only after demand and billing rules are clear.",
      "Use current tools for printable outputs instead of waiting for a future AI model pipeline.",
    ],
    steps: [
      { title: "Use the live STL path first", body: "Relief, logo, lithophane, and heightmap workflows already solve the printable use case for today." },
      { title: "Map future account features", body: "My Creations, credits, and history can wrap around a future generation pipeline once it exists." },
      { title: "Request the commercial path", body: "If you need batch, API, or team usage, send a request so the pricing model can be shaped by real demand." },
    ],
    faqs: [
      { q: "Is full AI 3D live now?", a: "No. This page is a roadmap and interest entry only. The current live output is still printable STL relief and related 2.5D workflows." },
      { q: "What should I use today?", a: "Use the current image-to-STL tools for reliable printable output, and use this page to track future AI 3D plans." },
    ],
  },
];

export const staticPages = [
  {
    slug: "samples",
    title: "Image to STL Examples",
    description: "Real image-to-STL examples with source images, generated STL previews, recommended settings, and downloadable STL files.",
  },
  {
    slug: "privacy",
    title: "Privacy Policy",
    description: "How PNGtoSTL handles uploads, conversion requests, analytics events, and contact messages.",
  },
  {
    slug: "terms",
    title: "Terms of Use",
    description: "Rules and limitations for using PNGtoSTL image-to-STL tools and generated files.",
  },
  {
    slug: "developers",
    title: "PNGtoSTL Developers and Batch Conversion",
    description: "Request early access for batch image-to-STL conversion, API workflows, commercial usage, higher limits, and repeatable STL generation support.",
  },
  {
    slug: "pricing",
    title: "PNGtoSTL Pricing",
    description: "Review current free image-to-STL access plus planned Pro, batch conversion, and API options for makers, schools, shops, and commercial workflows.",
  },
  {
    slug: "contact",
    title: "Contact PNGtoSTL",
    description: "Contact PNGtoSTL for support, feedback, bug reports, API access, batch conversion, and business inquiries.",
  },
];

export const sampleWorkflows = [
  {
    title: "Logo badge relief",
    category: "logo",
    categoryLabel: "Logo badge",
    input: "High-contrast PNG or SVG logo",
    output: "Raised logo STL with base plate",
    route: "/logo-to-stl",
    workflowCta: "Try logo badge settings",
    recommendedPreset: "Transparent logo relief · 95 mm width · 2.4 mm raised face · low smoothing",
    sourcePreview: "Black logo on transparent PNG",
    resultPreview: "Raised 95 mm badge plate",
    metrics: "22,300 triangles · 1.1 MB STL",
    fileSizeLabel: "1.1 MB",
    sourceImage: "/samples/logo-badge-premium-v4-source.png",
    previewImage: "/samples/logo-badge-premium-v4-preview.png",
    stlPath: "/samples/logo-badge-premium-v4.stl",
    settings: ["Mode: Transparent logo relief", "Width: 95 mm", "Relief height: 2.4 mm", "Smoothing: low"],
    bestFor: "badges, signs, makerspace labels, product marks",
    avoid: "photos, gradients, tiny text, complex mascot art",
  },
  {
    title: "Universal image relief",
    category: "relief",
    categoryLabel: "Relief",
    input: "PNG, JPG, WebP, GIF, or BMP with clear subject edges",
    output: "Front-facing relief STL with preview and metrics",
    route: "/image-to-stl",
    workflowCta: "Try universal relief settings",
    recommendedPreset: "Photo-style relief · 110 mm width · 2.4 mm relief height · 128 detail",
    sourcePreview: "Simple icon, line art, or high-contrast photo",
    resultPreview: "Relief surface with base thickness and downloadable STL",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/universal-relief-premium-v4-source.png",
    previewImage: "/samples/universal-relief-premium-v4-preview.png",
    stlPath: "/samples/universal-relief-premium-v4.stl",
    settings: ["Mode: Photo-style relief", "Width: 110 mm", "Relief height: 2.4 mm", "Detail: 128"],
    bestFor: "icons, line art, simple illustrations, high-contrast photos",
    avoid: "low contrast photos and images where the background is the subject",
  },
  {
    title: "Backlit lithophane panel",
    category: "lithophane",
    categoryLabel: "Lithophane",
    input: "Portrait or photo with balanced contrast",
    output: "Lithophane STL where thickness controls light",
    route: "/lithophane-generator",
    workflowCta: "Try lithophane panel settings",
    recommendedPreset: "Lithophane · 0.8-3.2 mm thickness · invert on · balanced contrast photo",
    sourcePreview: "Portrait photo with visible highlights and shadows",
    resultPreview: "Thin backlit panel, not a color print",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/lithophane-panel-premium-v4-source.png",
    previewImage: "/samples/lithophane-panel-premium-v4-preview.png",
    stlPath: "/samples/lithophane-panel-premium-v4.stl",
    settings: ["Mode: Lithophane", "Min thickness: 0.8 mm", "Max thickness: 3.2 mm", "Invert: on"],
    bestFor: "portraits, memorial photos, night lights, window panels",
    avoid: "very dark photos, blown-out highlights, cluttered backgrounds",
  },
  {
    title: "Heightmap surface",
    category: "heightmap",
    categoryLabel: "Heightmap",
    input: "Grayscale PNG heightmap",
    output: "Surface STL where brightness becomes height",
    route: "/heightmap-to-stl",
    workflowCta: "Try heightmap surface settings",
    recommendedPreset: "Heightmap terrain · 120 mm width · 6 mm max height · low smoothing",
    sourcePreview: "Black-to-white depth map, not a normal color photo",
    resultPreview: "Terrain-like surface with height variation",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/heightmap-surface-premium-v4-source.png",
    previewImage: "/samples/heightmap-surface-premium-v4-preview.png",
    stlPath: "/samples/heightmap-surface-premium-v4.stl",
    settings: ["Mode: Heightmap terrain", "Width: 120 mm", "Max height: 6 mm", "Smoothing: low"],
    bestFor: "terrain reliefs, texture plates, grayscale depth maps",
    avoid: "normal photos that are not intended as height data",
  },
  {
    title: "Rubber stamp relief",
    category: "logo",
    categoryLabel: "Stamp",
    input: "Black stamp artwork PNG with bold text and a clear border",
    output: "Compact raised stamp STL with printable letter strokes",
    route: "/logo-to-stl",
    workflowCta: "Try stamp relief settings",
    recommendedPreset: "Transparent logo relief · 80 mm width · 2.0 mm relief height · 112 detail",
    sourcePreview: "APPROVED / MAKER stamp graphic on transparent PNG",
    resultPreview: "Raised circular stamp relief with real STL mesh preview",
    metrics: "17,316 triangles · 0.8 MB STL",
    fileSizeLabel: "0.8 MB",
    sourceImage: "/samples/rubber-stamp-expanded-v1-source.png",
    previewImage: "/samples/rubber-stamp-expanded-v1-preview.png",
    stlPath: "/samples/rubber-stamp-expanded-v1.stl",
    settings: ["Mode: Transparent logo relief", "Width: 80 mm", "Relief height: 2.0 mm", "Detail: 112"],
    bestFor: "rubber stamp masters, embossing plates, approval marks, simple text seals",
    avoid: "thin serif fonts, long paragraphs, tiny date text, gray antialiased scans",
  },
  {
    title: "Coin relief medallion",
    category: "relief",
    categoryLabel: "Coin relief",
    input: "Round medallion line art with a central star and year text",
    output: "Circular relief STL suitable for a coin-style display print",
    route: "/image-to-stl",
    workflowCta: "Try coin relief settings",
    recommendedPreset: "Photo-style relief · 70 mm width · 2.2 mm relief height · 128 detail",
    sourcePreview: "High-contrast coin artwork with concentric rings",
    resultPreview: "Raised coin face rendered from the generated STL",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/coin-relief-expanded-v1-source.png",
    previewImage: "/samples/coin-relief-expanded-v1-preview.png",
    stlPath: "/samples/coin-relief-expanded-v1.stl",
    settings: ["Mode: Photo-style relief", "Width: 70 mm", "Relief height: 2.2 mm", "Detail: 128"],
    bestFor: "coins, challenge medallions, circular emblems, simple awards",
    avoid: "photorealistic faces, microscopic rim text, noisy metallic textures",
  },
  {
    title: "Workshop sign plate",
    category: "logo",
    categoryLabel: "Sign plate",
    input: "Bold text sign PNG with screw holes and a simple border",
    output: "Raised text sign plate STL with base geometry",
    route: "/png-to-stl",
    workflowCta: "Try sign plate settings",
    recommendedPreset: "Transparent PNG relief · 120 mm width · 1.8 mm relief height · 112 detail",
    sourcePreview: "WORKSHOP TOOLS sign artwork with transparent background",
    resultPreview: "Printable sign plate with readable raised letters",
    metrics: "14,396 triangles · 0.7 MB STL",
    fileSizeLabel: "0.7 MB",
    sourceImage: "/samples/sign-plate-expanded-v1-source.png",
    previewImage: "/samples/sign-plate-expanded-v1-preview.png",
    stlPath: "/samples/sign-plate-expanded-v1.stl",
    settings: ["Mode: Transparent logo relief", "Width: 120 mm", "Relief height: 1.8 mm", "Detail: 112"],
    bestFor: "garage labels, workshop signs, tool drawer labels, bold name plates",
    avoid: "narrow fonts, tiny secondary copy, low-resolution screenshots",
  },
  {
    title: "Pet photo relief",
    category: "relief",
    categoryLabel: "Pet relief",
    input: "High-contrast synthetic pet portrait with clear eyes and face outline",
    output: "Photo-style relief STL showing where portraits work and where detail is limited",
    route: "/jpg-to-stl",
    workflowCta: "Try pet photo relief settings",
    recommendedPreset: "Photo-style relief · 95 mm width · 2.0 mm relief height · high-contrast portrait",
    sourcePreview: "Simple pet portrait prepared for relief conversion",
    resultPreview: "Raised pet face relief with STL viewer proof",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/pet-photo-relief-expanded-v1-source.png",
    previewImage: "/samples/pet-photo-relief-expanded-v1-preview.png",
    stlPath: "/samples/pet-photo-relief-expanded-v1.stl",
    settings: ["Mode: Photo-style relief", "Width: 95 mm", "Relief height: 2.0 mm", "Detail: 128"],
    bestFor: "simple pet portraits, memorial plaques, high-contrast animal silhouettes",
    avoid: "busy backgrounds, dark fur on dark rooms, full-scene photos with tiny faces",
  },
  {
    title: "Portrait lithophane night light",
    category: "lithophane",
    categoryLabel: "Portrait lithophane",
    input: "Portrait photo prepared for a backlit lithophane panel",
    output: "Thin lithophane STL where thickness controls brightness",
    route: "/photo-to-lithophane",
    workflowCta: "Try portrait lithophane settings",
    recommendedPreset: "Lithophane · 0.8-3.0 mm thickness · invert on · portrait orientation",
    sourcePreview: "Grayscale portrait with clear facial contrast",
    resultPreview: "Warm translucent panel rendered from the generated STL",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/portrait-lithophane-expanded-v1-source.png",
    previewImage: "/samples/portrait-lithophane-expanded-v1-preview.png",
    stlPath: "/samples/portrait-lithophane-expanded-v1.stl",
    settings: ["Mode: Lithophane", "Min thickness: 0.8 mm", "Max thickness: 3.0 mm", "Invert: on"],
    bestFor: "night lights, gifts, portraits, memorial panels, window displays",
    avoid: "underexposed faces, blown-out highlights, cluttered backgrounds, color-only detail",
  },
  {
    title: "Terrain heightmap tile",
    category: "heightmap",
    categoryLabel: "Terrain tile",
    input: "Game-style grayscale terrain heightmap with hills and contour cues",
    output: "Raised terrain tile STL with visible ridges and printable slab thickness",
    route: "/heightmap-to-stl",
    workflowCta: "Try terrain tile settings",
    recommendedPreset: "Heightmap terrain · 110 mm width · 5.5 mm max height · 128 detail",
    sourcePreview: "Grayscale terrain map where white means higher elevation",
    resultPreview: "Terrain tile STL preview with height variation",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/terrain-tile-expanded-v1-source.png",
    previewImage: "/samples/terrain-tile-expanded-v1-preview.png",
    stlPath: "/samples/terrain-tile-expanded-v1.stl",
    settings: ["Mode: Heightmap terrain", "Width: 110 mm", "Max height: 5.5 mm", "Detail: 128"],
    bestFor: "terrain tiles, tabletop maps, texture plates, grayscale elevation data",
    avoid: "normal landscape photos, satellite color images, maps without height encoding",
  },
  {
    title: "Cookie cutter outline",
    category: "logo",
    categoryLabel: "Cookie cutter",
    input: "Bold transparent PNG outline with thick walls and simple curves",
    output: "Raised cutter-style STL outline with printable wall thickness",
    route: "/logo-to-stl",
    workflowCta: "Try cookie cutter settings",
    recommendedPreset: "Logo relief · 90 mm width · 2.6 mm wall height · low smoothing",
    sourcePreview: "Rounded cookie cutter outline with simple facial details",
    resultPreview: "Printable outline STL generated from the real converter",
    metrics: "12,972 triangles · 0.6 MB STL",
    fileSizeLabel: "0.6 MB",
    sourceImage: "/samples/cookie-cutter-expanded-v2-source.png",
    previewImage: "/samples/cookie-cutter-expanded-v2-preview.png",
    stlPath: "/samples/cookie-cutter-expanded-v2.stl",
    settings: ["Mode: Transparent logo relief", "Width: 90 mm", "Relief height: 2.6 mm", "Detail: 112"],
    bestFor: "cookie cutter outlines, fondant stamps, clay cutters, simple traced shapes",
    avoid: "thin decorative lines, complex silhouettes, tiny holes, photo-based art",
  },
  {
    title: "Keychain name tag",
    category: "logo",
    categoryLabel: "Keychain tag",
    input: "Simple name tag PNG with bold text, border, and keyring hole",
    output: "Raised keychain STL with connected letters and base plate",
    route: "/logo-to-stl",
    workflowCta: "Try keychain tag settings",
    recommendedPreset: "Logo relief · 85 mm width · 2.2 mm raised text · base plate on",
    sourcePreview: "MILO maker tag PNG with large text and keyring hole",
    resultPreview: "Printable tag STL with readable raised text",
    metrics: "11,180 triangles · 0.5 MB STL",
    fileSizeLabel: "0.5 MB",
    sourceImage: "/samples/keychain-tag-expanded-v2-source.png",
    previewImage: "/samples/keychain-tag-expanded-v2-preview.png",
    stlPath: "/samples/keychain-tag-expanded-v2.stl",
    settings: ["Mode: Transparent logo relief", "Width: 85 mm", "Relief height: 2.2 mm", "Detail: 112"],
    bestFor: "keychains, pet tags, maker badges, locker labels, simple name plates",
    avoid: "long names in tiny fonts, disconnected letters without a base, low-resolution screenshots",
  },
  {
    title: "Topographic coaster heightmap",
    category: "heightmap",
    categoryLabel: "Topo coaster",
    input: "Circular grayscale heightmap designed for a coaster-style relief tile",
    output: "Compact terrain coaster STL with visible contour-like height changes",
    route: "/heightmap-to-stl",
    workflowCta: "Try topo coaster settings",
    recommendedPreset: "Heightmap terrain · 100 mm width · 4.8 mm max height · 128 detail",
    sourcePreview: "Circular topo-style grayscale heightmap with contour rings",
    resultPreview: "Coaster-sized relief STL preview from the generated mesh",
    metrics: "65,532 triangles · 3.1 MB STL",
    fileSizeLabel: "3.1 MB",
    sourceImage: "/samples/topographic-coaster-expanded-v2-source.png",
    previewImage: "/samples/topographic-coaster-expanded-v2-preview.png",
    stlPath: "/samples/topographic-coaster-expanded-v2.stl",
    settings: ["Mode: Heightmap terrain", "Width: 100 mm", "Max height: 4.8 mm", "Detail: 128"],
    bestFor: "topographic coasters, terrain gifts, tabletop tokens, circular map reliefs",
    avoid: "normal color maps, text labels, satellite imagery, heightmaps with hard clipped edges",
  },
];

export type SampleWorkflow = (typeof sampleWorkflows)[number];

export function sampleWorkflowSlug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function getSampleWorkflow(slug: string | undefined, route?: string) {
  if (!slug) return null;
  const sample = sampleWorkflows.find((workflow) => sampleWorkflowSlug(workflow.title) === slug);
  if (!sample) return null;
  if (route && sample.route !== route) return null;
  return sample;
}

export function getTool(slug: string) {
  return tools.find((tool) => tool.slug === slug);
}

